# Generated by Django 4.2.6 on 2023-10-26 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='valid_form',
            new_name='valid_from',
        ),
    ]
